apiVersion: v1
kind: ConfigMap
metadata:
  name: mile-config1
  namespace: cloudmile
  labels:
    k8s-app: mile
data:
  nginx.conf: |
    events {
      worker_connections 2048;
    }
    http {
      server {
        listen 8888;
        listen [::]:8888;
        root /var/www/public;
        ignore_invalid_headers off;
        underscores_in_headers on;
        server_tokens off;
        location /v1/helloworld1 {
          add_header Content-Type text/html;
          return 200 '<html><body><h1>Hello World1</h1></body></html>';
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mile-config2
  namespace: cloudmile
  labels:
    k8s-app: mile
data:
  nginx.conf: |
    events {
      worker_connections 2048;
    }
    http {
      server {
        listen 8888;
        listen [::]:8888;
        root /var/www/public;
        ignore_invalid_headers off;
        underscores_in_headers on;
        server_tokens off;
        location /v1/helloworld2 {
          add_header Content-Type text/html;
          return 200 '<html><body><h1>Hello World2</h1></body></html>';
        }
      }
    }
